# Generated by Django 4.0 on 2021-12-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_expertteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertteam',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
