# Generated by Django 4.0 on 2021-12-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_expertteam_facebook_expertteam_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertteam',
            name='facebook',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AlterField(
            model_name='expertteam',
            name='instagram',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AlterField(
            model_name='expertteam',
            name='twitter',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
