# Generated by Django 4.0 on 2021-12-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_expertteam_facebook_alter_expertteam_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
